name: Build and Test

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.203

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build -c Release -o ./app/build

    - name: Test the project
      run: dotnet test
    
    - name: Publish the project
      run : dotnet publish -c Release -o ./app/publis

    - name: Setup `packer`
      uses: hashicorp/setup-packer@main
      id: setup

    - name: Run `packer init` for prerequisite image
      id: init-prerequisite
      run: packer init ./packer/prerequisite.pkr.hcl

    - name: Build `packer build` for prerequisite image
      id: build-prerequisite
      run: packer build ./packer/prerequisite.pkr.hcl

    - name: Run `packer init` for application image
      id: init-application
      run: packer init ./packer/application.pkr.hcl

    - name: Build `packer build` for application image
      id: build-application
      run: packer build ./packer/application.pkr.hc
